In [75]:
# Ans
import numpy as np
arr=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

In [4]:
arr.shape

(3, 4)

In [5]:
arr.size

12

In [6]:
arr.ndim

2

In [7]:
#Ans-
arr[0]

array([1, 2, 3, 4])

In [11]:
arr[2][3]

np.int64(12)

In [21]:
arr[0:3,[0,2]]



array([[ 1,  3],
       [ 5,  7],
       [ 9, 11]])

In [22]:
#Ans
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [23]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [25]:
np.random.rand(3,3)

array([[0.80214793, 0.74938013, 0.18610421],
       [0.20035621, 0.18989774, 0.43139719],
       [0.40721116, 0.52815682, 0.84751115]])

In [26]:
np.random.randn(3,3)

array([[ 1.95575411, -2.38570179,  0.15066201],
       [-0.722788  ,  1.17351941,  0.3038571 ],
       [-0.31206272,  0.47664153, -2.88715384]])

In [31]:
arr2=np.expand_dims(arr,axis=0)

In [32]:
arr2.ndim

3

converted 3 dimention from 2 dimention

In [33]:
arr.T

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

In [57]:
A=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
B=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
#1 Index wise multiplicatio
A*B


array([[  1,   4,   9,  16],
       [ 25,  36,  49,  64],
       [ 81, 100, 121, 144]])

In [61]:
#2 Matrix multiplication
A@B
#its not possible because n != p , matrix is (3,4) and (3,4) and 4 != 3
#that why it will give error

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 3 is different from 4)

In [63]:
#3 Add both the matrics
A+B

array([[ 2,  4,  6,  8],
       [10, 12, 14, 16],
       [18, 20, 22, 24]])

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [64]:
#4 Subtract matrix B from A
A-B

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [65]:
#5 Divide Matrix B by A
B/A

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [72]:
#Ans- byteswap() function to swap the byte order of an array.
arr.byteswap(inplace=True)

array([[ 72057594037927936, 144115188075855872, 216172782113783808,
        288230376151711744],
       [360287970189639680, 432345564227567616, 504403158265495552,
        576460752303423488],
       [648518346341351424, 720575940379279360, 792633534417207296,
        864691128455135232]])

In [83]:
a=np.array([[1,2],[3,4]])
np.linalg.inv(a)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

Inverse matrix

In [76]:
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [78]:
arr.reshape(2,6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [79]:
A=np.array([1,2,3])
B=np.array([[11,12,13],[14,15,16],[17,18,19]])

In [80]:
A+B

array([[12, 14, 16],
       [15, 17, 19],
       [18, 20, 22]])